import{a as b,i as l,S as v}from"./assets/vendor-1543de09.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const $="42454875-eb3549610f297412779ff13b6";let i=1,m=0;const f=15;async function h(o){i=1;const t=`https://pixabay.com/api/?key=${$}&q=${o}&image_type=photo&page=${i}&per_page=${f}&orientation=horizontal&safesearch=true`;try{const s=await b.get(t);if(!s.data)throw new Error("");const a=s.data;return m=a.totalHits,a.hits.length>0?(i+=1,a.hits):(l.error({position:"center",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),[])}catch{return l.error({position:"center",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),[]}}const E=new v(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function g(o){const t=document.getElementById("gallery");t.innerHTML=o.map(S).join(""),E.refresh()}function S(o){const{webformatURL:t,largeImageURL:s,tags:a,likes:e,views:r,comments:n,downloads:w}=o;return`<li class="card">
    <a href=${s} > <img
      src="${t}"
      alt="${a}"
    /> </a>
    <ul class="gallery">
      <li class="li-text"><span>Comments</span><span>${n}</span></li>
      <li class="li-text"><span>Views</span><span>${r}</span></li>
      <li class="li-text"><span>Likes</span><span>${e}</span></li>
      <li class="li-text"><span>Download</span><span>${w}</span></li>
    </ul>
  </li>`}const d=document.querySelector("#search-form"),y=document.querySelector(".hide"),u=document.querySelector(".loader-more");let p="";d.addEventListener("submit",async o=>{o.preventDefault(),p=d.elements.input.value,L();try{const t=await h(p);g(t),c(),q(),u.classList.remove("hide")}catch(t){console.log(t),c()}});u.addEventListener("click",async()=>{L();try{const o=await h(p);g(o),c();const s=document.querySelector(".card").getBoundingClientRect().height;window.scrollBy({left:0,top:s*2,behavior:"smooth"}),i*f>=m&&(u.classList.add("hide"),l.info({position:"center",title:"Information",message:"We're sorry, but you've reached the end of search results."}))}catch(o){console.log(o),c()}});function L(){y.classList.remove("hide")}function c(){y.classList.add("hide")}function q(){d.reset()}
//# sourceMappingURL=commonHelpers.js.map
