import{a as w,i as c,S as b}from"./assets/vendor-1543de09.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const v="42454875-eb3549610f297412779ff13b6";let l=1,f=0;const P=15;async function p(o,t){l=1;const a=`https://pixabay.com/api/?key=${v}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;try{const s=await w.get(a);if(!s.data)throw new Error("");const e=s.data;return f=e.totalHits,e.hits.length>0?(l+=1,e.hits):(c.error({position:"center",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),[])}catch{return c.error({position:"center",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),[]}}const E=new b(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});function h(o){const t=document.getElementById("gallery");t.innerHTML=o.map(S).join(""),E.refresh()}function S(o){const{webformatURL:t,largeImageURL:a,tags:s,likes:e,views:r,comments:n,downloads:L}=o;return`<li class="card">
    <a href=${a} > <img
      src="${t}"
      alt="${s}"
    /> </a>
    <ul class="gallery">
      <li class="li-text"><span>Comments</span><span>${n}</span></li>
      <li class="li-text"><span>Views</span><span>${r}</span></li>
      <li class="li-text"><span>Likes</span><span>${e}</span></li>
      <li class="li-text"><span>Download</span><span>${L}</span></li>
    </ul>
  </li>`}const d=document.querySelector("#search-form"),y=document.querySelector(".hide"),u=document.querySelector(".loader-more");let m="";d.addEventListener("submit",async o=>{o.preventDefault(),m=d.elements.input.value,g();try{const t=await p(m);h(t),i(),$(),u.classList.remove("hide")}catch(t){console.error("Error fetching images:",t),i()}});u.addEventListener("click",async()=>{g();try{const o=await p(m);h(o),i();const a=document.querySelector(".card").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"}),l*P>=f&&(u.classList.add("hide"),c.info({position:"center",title:"Information",message:"We're sorry, but you've reached the end of search results."}))}catch{i()}});function g(){y.classList.remove("hide")}function i(){y.classList.add("hide")}function $(){d.reset()}
//# sourceMappingURL=commonHelpers.js.map
